In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [80]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output/h0 dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5 input dim is [5,1,3] [seq,batch,feature]
inputs[0]

tensor([[-0.0114,  0.6726, -0.6892]])

In [29]:
# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
hidden

(tensor([[[-0.1423,  1.7084, -1.1981]]]),
 tensor([[[ 0.7044,  0.3299, -1.1728]]]))

In [35]:
### 每次单个元素输入
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print("out:",out.shape)
    print("hidden:",hidden[0].shape)

out: torch.Size([1, 1, 3])
hidden: torch.Size([1, 1, 3])
out: torch.Size([1, 1, 3])
hidden: torch.Size([1, 1, 3])
out: torch.Size([1, 1, 3])
hidden: torch.Size([1, 1, 3])
out: torch.Size([1, 1, 3])
hidden: torch.Size([1, 1, 3])
out: torch.Size([1, 1, 3])
hidden: torch.Size([1, 1, 3])


In [122]:
### 整体输入
# inputs = torch.cat((inputs[0],inputs[1],inputs[2]),1)
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5 input dim is [5,1,3] [seq,batch,feature]
inputs = torch.cat((inputs[0],inputs[1],inputs[2],inputs[3],inputs[4]),0)
inputs = inputs.view(len(inputs), 1, -1)# 此时inputs为[5,1,3]
### 注意：LSTM的hidden包括两部分h0和c0
h0 = torch.randn(1, 1, 3)# clean out hidden state
c0 = torch.randn(1, 1, 3)


In [127]:
lstm = nn.LSTM(input_size=3,hidden_size=3,num_layers=1)
out, (hn,cn) = lstm(inputs,(h0,c0))# 使用默认hidden
out.shape
# hidden[0].shape
# hidden[1].shape
hn.shape
cn.shape

torch.Size([1, 1, 3])